/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author sapat
 */
public class MainMenu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form SetUp_GUI
     */
    public MainMenu_GUI() {
        initComponents();
        Model.CRUD_DAO.refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("PARKINGLOT?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        vehicleQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT v FROM Vehicle v");
        vehicleList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : vehicleQuery.getResultList();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        currentTime_btn1 = new javax.swing.JButton();
        clean_btn2 = new javax.swing.JButton();
        exit_btn2 = new javax.swing.JButton();
        closeTicket_btn = new javax.swing.JButton();
        entryTime_txt2 = new javax.swing.JTextField();
        entryTime_lbl1 = new javax.swing.JLabel();
        licensePlate_lbl1 = new javax.swing.JLabel();
        licensePlate_txt2 = new javax.swing.JTextField();
        price_txt = new javax.swing.JTextField();
        price_lbl1 = new javax.swing.JLabel();
        exitTime_txt = new javax.swing.JTextField();
        exitTime_lbl1 = new javax.swing.JLabel();
        bg_lbl3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        exit_btn1 = new javax.swing.JButton();
        clean_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        consult_btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        entryTime_lbl = new javax.swing.JLabel();
        color_lbl = new javax.swing.JLabel();
        model_lbl = new javax.swing.JLabel();
        brand_lbl = new javax.swing.JLabel();
        licensePlate_lbl = new javax.swing.JLabel();
        licensePlate_txt1 = new javax.swing.JTextField();
        brand_txt1 = new javax.swing.JTextField();
        model_txt1 = new javax.swing.JTextField();
        color_txt1 = new javax.swing.JTextField();
        entryTime_txt1 = new javax.swing.JTextField();
        bg_lbl1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        currentTime_btn = new javax.swing.JButton();
        clean_btn1 = new javax.swing.JButton();
        exit_btn3 = new javax.swing.JButton();
        send_btn = new javax.swing.JButton();
        entryTime_lbl2 = new javax.swing.JLabel();
        color_lbl1 = new javax.swing.JLabel();
        model_lbl1 = new javax.swing.JLabel();
        brand_lbl1 = new javax.swing.JLabel();
        licensePlate_lbl2 = new javax.swing.JLabel();
        entryTime_txt = new javax.swing.JTextField();
        color_txt = new javax.swing.JTextField();
        model_txt = new javax.swing.JTextField();
        brand_txt = new javax.swing.JTextField();
        licensePlate_txt = new javax.swing.JTextField();
        bg_lbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setLayout(null);

        currentTime_btn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        currentTime_btn1.setText("SISTEMA");
        currentTime_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentTime_btn1ActionPerformed(evt);
            }
        });
        jPanel3.add(currentTime_btn1);
        currentTime_btn1.setBounds(380, 120, 100, 30);

        clean_btn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clean_btn2.setText("LIMPAR");
        clean_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clean_btn2ActionPerformed(evt);
            }
        });
        jPanel3.add(clean_btn2);
        clean_btn2.setBounds(370, 390, 110, 30);

        exit_btn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit_btn2.setText("SAIR");
        exit_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btn2ActionPerformed(evt);
            }
        });
        jPanel3.add(exit_btn2);
        exit_btn2.setBounds(400, 440, 80, 20);

        closeTicket_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        closeTicket_btn.setText("FECHAR TICKET");
        closeTicket_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeTicket_btnActionPerformed(evt);
            }
        });
        jPanel3.add(closeTicket_btn);
        closeTicket_btn.setBounds(170, 390, 170, 30);

        entryTime_txt2.setBackground(new java.awt.Color(204, 204, 204));
        entryTime_txt2.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        entryTime_txt2.setEnabled(false);
        jPanel3.add(entryTime_txt2);
        entryTime_txt2.setBounds(120, 160, 360, 30);

        entryTime_lbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        entryTime_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        entryTime_lbl1.setText("ENTRADA:");
        entryTime_lbl1.setToolTipText("");
        jPanel3.add(entryTime_lbl1);
        entryTime_lbl1.setBounds(10, 160, 110, 30);

        licensePlate_lbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        licensePlate_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        licensePlate_lbl1.setText("PLACA:");
        licensePlate_lbl1.setToolTipText("");
        jPanel3.add(licensePlate_lbl1);
        licensePlate_lbl1.setBounds(10, 80, 80, 30);

        licensePlate_txt2.setText("INSIRA PLACA DO VEICULO (ABC1D234 ou ABC1234)");
        jPanel3.add(licensePlate_txt2);
        licensePlate_txt2.setBounds(120, 80, 360, 30);

        price_txt.setBackground(new java.awt.Color(204, 204, 204));
        price_txt.setForeground(new java.awt.Color(255, 51, 51));
        price_txt.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        price_txt.setEnabled(false);
        jPanel3.add(price_txt);
        price_txt.setBounds(120, 200, 360, 30);

        price_lbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        price_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        price_lbl1.setText("VALOR:");
        price_lbl1.setToolTipText("");
        jPanel3.add(price_lbl1);
        price_lbl1.setBounds(10, 200, 110, 30);

        exitTime_txt.setText("HORARIO DE SAIDA DO VEICULO (00:00:00)");
        jPanel3.add(exitTime_txt);
        exitTime_txt.setBounds(120, 120, 250, 30);

        exitTime_lbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitTime_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        exitTime_lbl1.setText("SAIDA:");
        exitTime_lbl1.setToolTipText("");
        jPanel3.add(exitTime_lbl1);
        exitTime_lbl1.setBounds(10, 120, 110, 30);

        bg_lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BG2.png"))); // NOI18N
        jPanel3.add(bg_lbl3);
        bg_lbl3.setBounds(0, 0, 500, 500);

        jTabbedPane1.addTab("FECHAR TICKET", jPanel3);

        jPanel1.setLayout(null);

        exit_btn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit_btn1.setText("SAIR");
        exit_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(exit_btn1);
        exit_btn1.setBounds(400, 440, 80, 20);

        clean_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clean_btn.setText("LIMPAR");
        clean_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clean_btnActionPerformed(evt);
            }
        });
        jPanel1.add(clean_btn);
        clean_btn.setBounds(330, 390, 140, 30);

        update_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        update_btn.setText("ALTERAR");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel1.add(update_btn);
        update_btn.setBounds(180, 390, 140, 30);

        delete_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(255, 0, 0));
        delete_btn.setText("EXCLUIR");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jPanel1.add(delete_btn);
        delete_btn.setBounds(180, 430, 140, 30);

        consult_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        consult_btn.setText("CONSULTAR");
        consult_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consult_btnActionPerformed(evt);
            }
        });
        jPanel1.add(consult_btn);
        consult_btn.setBounds(30, 390, 140, 30);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vehicleList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${licensePlate}"));
        columnBinding.setColumnName("Placa");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${brand}"));
        columnBinding.setColumnName("Marca");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${model}"));
        columnBinding.setColumnName("Modelo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${color}"));
        columnBinding.setColumnName("Cor");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 70, 480, 110);

        entryTime_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        entryTime_lbl.setForeground(new java.awt.Color(255, 255, 255));
        entryTime_lbl.setText("ENTRADA:");
        entryTime_lbl.setToolTipText("");
        jPanel1.add(entryTime_lbl);
        entryTime_lbl.setBounds(10, 350, 110, 30);

        color_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        color_lbl.setForeground(new java.awt.Color(255, 255, 255));
        color_lbl.setText("COR:");
        color_lbl.setToolTipText("");
        jPanel1.add(color_lbl);
        color_lbl.setBounds(10, 310, 80, 30);

        model_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        model_lbl.setForeground(new java.awt.Color(255, 255, 255));
        model_lbl.setText("MODELO:");
        model_lbl.setToolTipText("");
        jPanel1.add(model_lbl);
        model_lbl.setBounds(10, 270, 100, 30);

        brand_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        brand_lbl.setForeground(new java.awt.Color(255, 255, 255));
        brand_lbl.setText("MARCA:");
        brand_lbl.setToolTipText("");
        jPanel1.add(brand_lbl);
        brand_lbl.setBounds(10, 230, 80, 30);

        licensePlate_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        licensePlate_lbl.setForeground(new java.awt.Color(255, 255, 255));
        licensePlate_lbl.setText("PLACA:");
        licensePlate_lbl.setToolTipText("");
        jPanel1.add(licensePlate_lbl);
        licensePlate_lbl.setBounds(10, 190, 80, 30);

        licensePlate_txt1.setText("INSIRA PLACA DO VEICULO (ABC1D234 ou ABC1234)");
        jPanel1.add(licensePlate_txt1);
        licensePlate_txt1.setBounds(120, 190, 360, 30);

        brand_txt1.setText("MARCA");
        jPanel1.add(brand_txt1);
        brand_txt1.setBounds(120, 230, 360, 30);

        model_txt1.setText("MODELO");
        jPanel1.add(model_txt1);
        model_txt1.setBounds(120, 270, 360, 30);

        color_txt1.setText("COR");
        jPanel1.add(color_txt1);
        color_txt1.setBounds(120, 310, 360, 30);

        entryTime_txt1.setText("HORARIO DE ENTRADA (00:00:00)");
        jPanel1.add(entryTime_txt1);
        entryTime_txt1.setBounds(120, 350, 360, 30);

        bg_lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg3.png"))); // NOI18N
        jPanel1.add(bg_lbl1);
        bg_lbl1.setBounds(0, 0, 500, 500);

        jTabbedPane1.addTab("CONSULTAR/ALTERAR/EXCLUIR", jPanel1);

        jPanel2.setLayout(null);

        currentTime_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        currentTime_btn.setText("SISTEMA");
        currentTime_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentTime_btnActionPerformed(evt);
            }
        });
        jPanel2.add(currentTime_btn);
        currentTime_btn.setBounds(370, 290, 100, 30);

        clean_btn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clean_btn1.setText("LIMPAR");
        clean_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clean_btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(clean_btn1);
        clean_btn1.setBounds(360, 370, 110, 40);

        exit_btn3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit_btn3.setText("SAIR");
        exit_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(exit_btn3);
        exit_btn3.setBounds(400, 440, 80, 20);

        send_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        send_btn.setText("CADASTRAR");
        send_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_btnActionPerformed(evt);
            }
        });
        jPanel2.add(send_btn);
        send_btn.setBounds(160, 370, 170, 40);

        entryTime_lbl2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        entryTime_lbl2.setForeground(new java.awt.Color(255, 255, 255));
        entryTime_lbl2.setText("ENTRADA:");
        entryTime_lbl2.setToolTipText("");
        jPanel2.add(entryTime_lbl2);
        entryTime_lbl2.setBounds(10, 290, 110, 30);

        color_lbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        color_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        color_lbl1.setText("COR:");
        color_lbl1.setToolTipText("");
        jPanel2.add(color_lbl1);
        color_lbl1.setBounds(10, 240, 80, 30);

        model_lbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        model_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        model_lbl1.setText("MODELO:");
        model_lbl1.setToolTipText("");
        jPanel2.add(model_lbl1);
        model_lbl1.setBounds(10, 190, 100, 30);

        brand_lbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        brand_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        brand_lbl1.setText("MARCA:");
        brand_lbl1.setToolTipText("");
        jPanel2.add(brand_lbl1);
        brand_lbl1.setBounds(10, 140, 80, 30);

        licensePlate_lbl2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        licensePlate_lbl2.setForeground(new java.awt.Color(255, 255, 255));
        licensePlate_lbl2.setText("PLACA:");
        licensePlate_lbl2.setToolTipText("");
        jPanel2.add(licensePlate_lbl2);
        licensePlate_lbl2.setBounds(10, 90, 80, 30);

        entryTime_txt.setText("HORARIO DE ENTRADA DO VEICULO (00:00:00)");
        entryTime_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryTime_txtActionPerformed(evt);
            }
        });
        jPanel2.add(entryTime_txt);
        entryTime_txt.setBounds(110, 290, 250, 30);

        color_txt.setText("INSIRA A COR DO VEICULO");
        jPanel2.add(color_txt);
        color_txt.setBounds(110, 240, 360, 30);

        model_txt.setText("INSIRA O MODELO DO VEICULO");
        jPanel2.add(model_txt);
        model_txt.setBounds(110, 190, 360, 30);

        brand_txt.setText("INSIRA A MARCA DO VEICULO");
        jPanel2.add(brand_txt);
        brand_txt.setBounds(110, 140, 360, 30);

        licensePlate_txt.setText("INSIRA PLACA DO VEICULO (ABC1D234 ou ABC1234)");
        jPanel2.add(licensePlate_txt);
        licensePlate_txt.setBounds(110, 90, 360, 30);

        bg_lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BG.png"))); // NOI18N
        jPanel2.add(bg_lbl2);
        bg_lbl2.setBounds(0, 0, 500, 500);

        jTabbedPane1.addTab("CADASTRAR", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("FECHAR TICKET");

        bindingGroup.bind();

        setSize(new java.awt.Dimension(500, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void send_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_btnActionPerformed
        String licensePlate = licensePlate_txt.getText();
        String brand = brand_txt.getText();
        String model = model_txt.getText();
        String color = color_txt.getText();
        String entryTime = entryTime_txt.getText();
        Model.CRUD_DAO.create(licensePlate, brand, model, color, entryTime);
    }//GEN-LAST:event_send_btnActionPerformed

    private void consult_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consult_btnActionPerformed
        System.out.println("A ser consultado: " + licensePlate_txt1.getText());
        Model.CRUD_DAO.read(licensePlate_txt1.getText());
    }//GEN-LAST:event_consult_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        String licensePlate = licensePlate_txt1.getText();
        String brand = brand_txt1.getText();
        String model = model_txt1.getText();
        String color = color_txt1.getText();
        String entryTime = entryTime_txt1.getText();

        Model.CRUD_DAO.update(licensePlate, brand, model, color, entryTime);
    }//GEN-LAST:event_update_btnActionPerformed

    private void clean_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clean_btnActionPerformed
        Model.Funcs_DAO.cleanReadUpdateDeleteFields();
    }//GEN-LAST:event_clean_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        System.out.println("A ser deletado: " + licensePlate_txt1.getText());
        Model.CRUD_DAO.delete(licensePlate_txt1.getText());
    }//GEN-LAST:event_delete_btnActionPerformed

    private void closeTicket_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeTicket_btnActionPerformed
        String licensePlate = licensePlate_txt2.getText();
        String exitTime = exitTime_txt.getText();
        Model.CRUD_DAO.closeTicket(licensePlate, exitTime);
    }//GEN-LAST:event_closeTicket_btnActionPerformed

    private void exit_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btn1ActionPerformed
        Model.Funcs_DAO.exit();
    }//GEN-LAST:event_exit_btn1ActionPerformed

    private void exit_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btn2ActionPerformed
        Model.Funcs_DAO.exit();
    }//GEN-LAST:event_exit_btn2ActionPerformed

    private void exit_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btn3ActionPerformed
        Model.Funcs_DAO.exit();
    }//GEN-LAST:event_exit_btn3ActionPerformed

    private void clean_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clean_btn1ActionPerformed
        Model.Funcs_DAO.cleanCreateFields();
    }//GEN-LAST:event_clean_btn1ActionPerformed

    private void clean_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clean_btn2ActionPerformed
        Model.Funcs_DAO.cleanCloseTicketFields();
    }//GEN-LAST:event_clean_btn2ActionPerformed

    private void currentTime_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentTime_btnActionPerformed
        LocalTime currentTime = LocalTime.now();
        String formattedTime = currentTime.format(DateTimeFormatter.ofPattern("HH:mm:ss"));
        System.out.println(formattedTime);
        entryTime_txt.setText(formattedTime);
    }//GEN-LAST:event_currentTime_btnActionPerformed

    private void entryTime_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryTime_txtActionPerformed
        
    }//GEN-LAST:event_entryTime_txtActionPerformed

    private void currentTime_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentTime_btn1ActionPerformed
        LocalTime currentTime = LocalTime.now();
        String formattedTime = currentTime.format(DateTimeFormatter.ofPattern("HH:mm:ss"));
        System.out.println(formattedTime);
        exitTime_txt.setText(formattedTime);
    }//GEN-LAST:event_currentTime_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_lbl1;
    private javax.swing.JLabel bg_lbl2;
    private javax.swing.JLabel bg_lbl3;
    private javax.swing.JLabel brand_lbl;
    private javax.swing.JLabel brand_lbl1;
    public static javax.swing.JTextField brand_txt;
    public static javax.swing.JTextField brand_txt1;
    public static javax.swing.JButton clean_btn;
    public static javax.swing.JButton clean_btn1;
    public static javax.swing.JButton clean_btn2;
    public static javax.swing.JButton closeTicket_btn;
    private javax.swing.JLabel color_lbl;
    private javax.swing.JLabel color_lbl1;
    public static javax.swing.JTextField color_txt;
    public static javax.swing.JTextField color_txt1;
    public static javax.swing.JButton consult_btn;
    public static javax.swing.JButton currentTime_btn;
    public static javax.swing.JButton currentTime_btn1;
    public static javax.swing.JButton delete_btn;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel entryTime_lbl;
    private javax.swing.JLabel entryTime_lbl1;
    private javax.swing.JLabel entryTime_lbl2;
    public static javax.swing.JTextField entryTime_txt;
    public static javax.swing.JTextField entryTime_txt1;
    public static javax.swing.JTextField entryTime_txt2;
    private javax.swing.JLabel exitTime_lbl1;
    public static javax.swing.JTextField exitTime_txt;
    public static javax.swing.JButton exit_btn1;
    public static javax.swing.JButton exit_btn2;
    public static javax.swing.JButton exit_btn3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JLabel licensePlate_lbl;
    private javax.swing.JLabel licensePlate_lbl1;
    private javax.swing.JLabel licensePlate_lbl2;
    public static javax.swing.JTextField licensePlate_txt;
    public static javax.swing.JTextField licensePlate_txt1;
    public static javax.swing.JTextField licensePlate_txt2;
    private javax.swing.JLabel model_lbl;
    private javax.swing.JLabel model_lbl1;
    public static javax.swing.JTextField model_txt;
    public static javax.swing.JTextField model_txt1;
    private javax.swing.JLabel price_lbl1;
    public static javax.swing.JTextField price_txt;
    public static javax.swing.JButton send_btn;
    public static javax.swing.JButton update_btn;
    private java.util.List<View.Vehicle> vehicleList;
    private javax.persistence.Query vehicleQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
